# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7fcee18f68b9709925bda98748850095ed1101c0ad20336fc6eab736fe69a1085c45544b6784b9c0697f28539ccb4d3d8005529e3b12e36bb0c5a12335831568

test:
  secret_key_base: 2d776147e9b3ae8a5490c4e7644fe35a88a2996f09a0c5d5a2752b0a0dc9a5597ec1984a32337c967dae996dd591e9bc7a50dc29bdbf92c69960f0ab725da120

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
